dist: trusty
language: node_js
node_js:
 - "10"
before_install:
  - npm i -g npm
before_script:
 - yarn danger ci
 - npm install grunt-cli -g
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5
script:
- npm run test:e2e
- npm run test:unit
- grunt
after_script:
 - npm list
cache:
 directories:
  - node_modules
